/*	Project Euler #002
 *	Author: Tomos Ewe - tomosewe@gmail.com
 *
 *	Even Fibonacci numbers
 *	--------------------
 *	For all values in the Fibonacci sequence that do not exceed 4 million,
 *	find the sum of all the even-valued terms.
 *	
 *	The Fibonacci sequence is where each new term is generated by adding the previous two terms.
 *	By starting with 1 and 2, the first 10 terms will be:
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 */

class Euler002 {     
	private final int max = 4000000;
	private int first = 1;
	private int second = 2;
	private int third = 0;
	private int sum = 0;
		
	public Euler002() {}
        
	public int run() {
		sum = second;	
		while (first < max) {
			third = first + second;
			first = second;
			second = third;
			if (third < max && third % 2 == 0) {
				sum += third;
			}				
		}
		return(sum);
	}     
}